"""RudderStack exporter: builds a RudderStack Tracking Plan document.

RudderStack's Tracking Plan API (https://www.rudderstack.com/docs/dashboard-guides/tracking-plans/)
is deliberately Segment-Protocols-compatible (RudderStack explicitly
supports importing Segment tracking plans and RudderTyper specs), so the
document shape mirrors segment.py's `rules.events[]`/JSON-Schema structure,
but with RudderStack-specific fields RudderStack's own API adds on top:
`eventType` (RudderStack's `track`/`page`/`identify`/`screen`/`group` event
classification) and `creationType`.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List

from pytagmanager.export._taxonomy import canonical_event
from pytagmanager.recommend.models import TrackingRecommendation

# canonical event key -> (RudderStack event name, JSON-Schema properties, required list).
_RUDDERSTACK_EVENT_SPECS = {
    "add_to_cart": ("Product Added", {"product_id": {"type": "string"}}, ["product_id"]),
    "start_trial": ("Trial Started", {"plan": {"type": "string"}}, []),
    "subscribe": ("Subscription Started", {"plan": {"type": "string"}}, []),
    "generate_lead": ("Lead Generated", {"lead_source": {"type": "string"}}, []),
    "login": ("Signed In", {"method": {"type": "string"}}, []),
    "content_engagement": ("Content Viewed", {"content_type": {"type": "string"}}, []),
    "search": ("Products Searched", {"query": {"type": "string"}}, []),
}
_DEFAULT_RUDDERSTACK_EVENT = ("Custom Event Triggered", {}, [])


def build_rudderstack_tracking_plan(recommendations: List[TrackingRecommendation]) -> dict:
    """Build `{"name": ..., "rules": {"events": [...]}}`, RudderStack's
    Tracking Plan resource shape: each event carries `eventType: "track"`
    (interactions PyTagManager recommends -- clicks, form submits -- are all
    RudderStack `track` calls, not `page`/`identify`/`screen`/`group`),
    `creationType: "AUTO"` (RudderStack's flag for tracking-plan entries
    generated by tooling rather than typed by hand in the dashboard), and a
    JSON-Schema `properties` block matching RudderStack's Segment-compatible
    validation format.
    """
    events = []
    for rec in recommendations:
        canonical = canonical_event(rec)
        name, props, required = _RUDDERSTACK_EVENT_SPECS.get(canonical, _DEFAULT_RUDDERSTACK_EVENT)

        events.append(
            {
                "name": name,
                "eventType": "track",
                "creationType": "AUTO",
                "description": rec.rationale,
                "rules": {
                    "properties": {
                        "properties": {
                            "type": "object",
                            "properties": props,
                            "required": required,
                        },
                    },
                },
                "metadata": {
                    "trigger_type": rec.trigger_type,
                    "selector": rec.selector,
                    "business_objective": rec.business_objective,
                    "confidence": rec.confidence,
                    "page_url": rec.page_url,
                },
            }
        )

    return {
        "name": "PyTagManager Tracking Plan",
        "rules": {"events": events},
    }


def export_rudderstack_json(recommendations: List[TrackingRecommendation], path: str) -> None:
    plan = build_rudderstack_tracking_plan(recommendations)
    Path(path).write_text(json.dumps(plan, indent=2))
